# Generated by Django 5.0.4 on 2024-08-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
