# Generated by Django 5.1 on 2024-08-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_city_designation_leavetype_state_employee_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fro', models.DateTimeField()),
                ('to', models.DateField(null=True)),
                ('num_of_days', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('cancle', 'cancle'), ('rejected', 'rejected')], default='pending', max_length=30)),
                ('description', models.TextField(null=True)),
                ('emp_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
                ('leavetype_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
            ],
        ),
    ]
