# Generated by Django 5.1 on 2024-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reset_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
