# Generated by Django 5.1 on 2024-10-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_employee_reset_token_employee_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='security_answer_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_answer_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_answer_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
