# Generated by Django 5.1.2 on 2024-10-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_employee_security_answer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='annual_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='days_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
